### ISSUE TITLE
GetRidOfurlCharacters

### ISSUE THREAD

**Issue by crushedice2000** [esp8266/Basic#15]
Hi! Could you say me what problem are you facing with my PR?

**Comment by mmiscool** [comment]
upon testing it was not catching several symbols. I cant quite remeber which ones but try some of the following.

multiple spces
+-/*|!@#$%^&*)(*&

I was doing some thing significant.

**Comment by crushedice2000** [comment]
@mmiscool: Could you send me a problematic urlencoded string? I don't see any problem.

**Comment by mmiscool** [comment]
function has been working for past several versions
