### ISSUE TITLE
New function to split the arguments

### ISSUE THREAD

**Issue by cicciocb** [esp8266/Basic#24]
Mike,
you will find here the new function included into a sample of commands.ino.
you can refer to 3 commands done as example :  
testparam that will print the parameters; you can use it to understand and check how the splitter works
slider
button
[Commands.zip.txt](https://github.com/esp8266/Basic/files/281268/Commands.zip.txt)

remove the txt from the file as it's a zip

**Comment by mmiscool** [comment]
This has been incorperated
