### ISSUE TITLE
Change the serial baud rate

### ISSUE THREAD

**Issue by crushedice2000** [esp8266/Basic#3]
Hi! I think that this basic interpreter lacks a cool feature. What about changing serial port baud rate? Wouldn't be hard to implement a `baudrate {integer}`command, no?

**Comment by mmiscool** [comment]
Added to v1.44

**Comment by mmiscool** [comment]
https://github.com/esp8266/Basic/commit/e3d1c06b45635245add95058b618720f00e5d503
