### ISSUE TITLE
esp8266-12e ap mode startup problem

### ISSUE THREAD

**Issue by ajinkyaw** [esp8266/Basic#30]
hi guys, 
i am sharing my circuit diagram here  
the problem i am facing is , i need to reset the esp8266-12e module multiple times to make it work (make it work means starting it in Ap mode as coded ). sometimes it works sometime it doesnt.
please post the suggestions if any one knows.
![mycircuit](https://cloud.githubusercontent.com/assets/14973613/21052734/6fab81f2-be4c-11e6-8687-a35f38dda234.png)

**Comment by mmiscool** [comment]
Have you tried a beefier power supply?
