### ISSUE TITLE
 Editor Interface Required for ESP8266 BASIC 3.0

### ISSUE THREAD

**Issue by flywire** [esp8266/Basic#31]
Descriptions are needed of current Editor Interface Screen options.

A ESP8266 Basic Reference is required for more than just the language.

**Comment by mmiscool** [comment]
Please see following page
https://www.esp8266basic.com/editor-interface.html

**Comment by flywire** [comment]
This is out of date. There is not enough information on the settings page which is critical given the fact that all programming is done in the web browser.

**Comment by mmiscool** [comment]
Updated the page there. Closing this issue
