### ISSUE TITLE
+ipd missing 

### ISSUE THREAD

**Issue by VRVishnu** [esp8266/Basic#36]
hi, I'm using my esp8266 module as a TCP server. when sending data from multiple client devices it oftenly shows data missing, In that cases +ipd is missing in my received data. expecting your valuable suggetions and solutions on this issue.
My settings are as follows:

AT+CWMODE=1
AT+CWDHCP=0,0
AT+CIPSTA="STA_IP","GATEWAY","SUBNET MASK"
AT+CWJAP="SSID","PASS_WORD"
AT+CIPMUX=1
AT+CIPSERVER=1,2000 I'M USING PORT 2000
AT+CIPSTO=0

AFTER the setting starts connect to the device from client and sends data.. the +ipd missing occures when data receives frommultiple clients...........please help me to resolve this issue...

**Comment by mmiscool** [comment]
This seems to be for the at command firmware and not for ESP Basic.
