### ISSUE TITLE
Could be replaced the use of the String class with char?

### ISSUE THREAD

**Issue by crushedice2000** [esp8266/Basic#5]
Hi! I've read [a post](http://hacking.majenko.co.uk/the-evils-of-arduino-strings) on a blog saying that the use of Arduino `String` class is a bad idea. Wouldn't be better to replace them by `char` and `char*`?

**Comment by mmiscool** [comment]
This is not too big of a problem on the esp. I am not the best c/c++ coder so it might make it harder to maintain for my self.

Encapsulated in side functions should be fine how ever because those are limited in scope

**Comment by crushedice2000** [comment]
Ok, I *never* used C/C++ I'm a mid-level Python programmer and a high-level Bash and Gambas 3 programmer. I never used C/C++ with a serious aim.

However you could say me which side functions could we convert...
