### ISSUE TITLE
The variable and function names aren't serious (or I believe so)

### ISSUE THREAD

**Issue by crushedice2000** [esp8266/Basic#7]
This is not a issue really (as in doesn't affect the code), but I think that should be fixed to improve readability.

Humorous examples (a selection of the best ones):

    GetRidOfurlCharacters
    WhatIwillReturn
    GetMeThatVar
    
Serious typos found:
    GraphicsEliments
    PinDesignaor
    VarialbeLookup

---

Dear maintainer:

  What about using global *Find and Replace* dialog of your favorite text editor to fix these things?

:stuck_out_tongue_winking_eye:

**Comment by mmiscool** [comment]
A bit of humor. Also lack of spell check in code. Mabe I am a bit dyslexic

**Comment by crushedice2000** [comment]
I have to recognize that they are humorous :smile: (even for non-native English speakers -as me-). However I think that this could be a serious pain for future contributors (even me).

I think you should put the humorous part in the comments and not in the code (this is my opinion, however, you're the project owner). :stuck_out_tongue:
