### ISSUE TITLE
Styling the web interface

### ISSUE THREAD

**Issue by crushedice2000** [esp8266/Basic#9]
What about adding a small CSS to the web interface to make it look better?

**Comment by mmiscool** [comment]
Could be nice. A bit concerned about binary size increases but would be fine to do. 

The basic interface today is rather bare bones and simple. Works on laptops. Tables and phones. Want to make sure it stays simple.

**Comment by crushedice2000** [comment]
We could do a minimized CSS and then put the *big and commented* version here on GitHub... So the size is not a major deal (or I think so).

I respect the simplicity, but a bit of style would be great :smile:

**Comment by mmiscool** [comment]
this has been done.

Upload a file named skin.css using the file manager. Interface can now be skinned.
